<?php
/**
 * Language definitions. Generated by the Blesta Translator
 * 
 * @package blesta
 * @version 3.6.0
 * @copyright Copyright (c) 2016, Phillips Data, Inc.
 * @license http://www.blesta.com/license/ The Blesta License Agreement
 * @link http://www.blesta.com/ Blesta
 */

$lang['Cwp.name'] = "Centos Web Panel";

$lang['Cwp.add_module_group'] = "Adicionar Grupo de Servidor";
$lang['Cwp.manage.module_groups_title'] = "Grupo de Servidores";
$lang['Cwp.manage.module_groups_heading.servers'] = "Contagem Servidor";
$lang['Cwp.manage.module_rows.confirm_delete'] = "Tem certeza de que deseja apagar este servidor?";
$lang['Cwp.add_row.remove_name_server'] = "Remover";
$lang['Cwp.edit_row.name_server'] = "Nome do Servidor %1\$s"; // %1$s is the name server number (e.g. 3)
$lang['Cwp.row_meta.host_name'] = "Hostname";
$lang['Cwp.package_fields.type'] = "Tipo de Conta";
$lang['Cwp.package_fields.acl'] = "Lista de Controlo de Acesso";
$lang['Cwp.package_fields.acl_default'] = "Predefinido";
$lang['Cwp.service_field.username'] = "Nome de utilizador";
$lang['Cwp.tab_stats.info.domain'] = "Domínio";
$lang['Cwp.tab_stats.disk_heading.limit'] = "Limite";
$lang['Cwp.service_info.password'] = "Password";
$lang['Cwp.service_info.server'] = "Servidor";
$lang['Cwp.tab_client_stats'] = "Estatísticas";
$lang['Cwp.!error.Cwp_password.matches'] = "A Password e a Confirmação da Password não coincidem.";
$lang['Cwp.tab_client_actions'] = "Ações";
?>